### ISSUE TITLE
Contribution Guidelines?

### ISSUE THREAD

**Issue by paultsw** [sail-sg/autofd#10]
Hi, this repo is really interesting to me and I would like to consider making additions, improvements, or extensions in the next month.

Is this going to be an actively-maintained project moving forward? Are contributions/extensions welcome?

Additionally, are there any contribution guidelines that I ought to follow? For instance, Google has the following code of conduct for contributions: https://opensource.google/conduct/

Thanks!

**Comment by mavenlin** [comment]
Hi @paultsw ,

Thanks for your interest.

Currently we don't have an explicit roadmap, but we use this project in our internal quantum chemistry project and in our other project https://github.com/sail-sg/jax_xc, so yes we'll update this repo time to time to keep it up to date.

This project itself as a standalone also has lots to be improved, there are several items I mentioned in the paper, but there is no timeline to it, I guess I will implement them when there's a need from our quantum chemistry project.

1. inverse transformation.
2. less strict shape requirements.
3. partial operator that mix function and array. (which is already improved in the current release than when the paper was published.)
4. optimization at the operator jaxpr graph, e.g. automatically apply taylor mode for high order differentiation.

If you have any new or improvement ideas, your contributions are more than welcome and very much appreciated. Feel free to open discussions, issues or pull requests.

As for the code of conduct, I believe it is usually used for preventing abusive behaviours, we would add in the future if there are more people collaborating in this project.

**Comment by paultsw** [comment]
Hi @mavenlin ,

Thanks for the reply! That's wonderful news. And of course, I have absolutely zero intent towards any abusive behaviors :sweat_smile: 

I have a bit on my plate at the moment, but I will look over the aforementioned items you've listed and see if I have the capacity to make any reasonable contribution proposals via discussion/pull request in the following month (June/July). I would absolutely love to contribute code if possible. For clarity, further development of `autofd` would benefit some personal experiments that I am doing on physical modeling, hence my interest.

Once again, I appreciate the reply, and I will study the above carefully. Unless there are other aspects to mention, I'd be fine with closing out this issue. Is that fine?

**Comment by mavenlin** [comment]
@paultsw Excited and looking forward to how this could be applied to physical modeling. I'll close this issue for now.
